### ISSUE TITLE
dbClient.ConnectionStringContainsKey not working as expected

### ISSUE THREAD

**Issue by Umc34** [rgarrison12345/ADONetHelper#1]
Creating DbClient with : 

 _dbClient = new DbClient(connectionString, provider); //provider passing with string here

however when we check that "string" inside connstr, it returns true despite string not available.

**dataBaseConnectionStringKey = "Database" //for example 

 if (!_dbClient.ConnectionStringContainsKey(dataBaseConnectionStringKey)) : returns true**

thanks in advance.

**Comment by rgarrison12345** [comment]
What is the name of the ADO.Net provider you're using?  The code just calls the DbConnectionStringBuilder contains key function which would be implemented by that provider.

**Comment by Umc34** [comment]
we are using all with factory pattern,
Npgsql, Microsoft.Data.SqlClient, MySqlConnector, Oracle.ManagedDataAccess.Core

method with two string as parameter (connstr and providerkey)
using (_dbClient = new DbClient("server=*****;port=5432;username=postgres;password=****;database=testdb;command timeout=0;keepalive=30;", "Npgsql"))

**Comment by rgarrison12345** [comment]
I checked out the npgsqlconnectionringbuilder class, it looks like that the has connection string key is misleading.  Really the class is determining if the passed in keyword is an allowable keyword for a connection string in npgsql.  Not is the current connection string that the builder class is composed of, contains the passed in key.

The code is performing as expected because it just delegates the work down to the provider specific implementation of dbconnectionstringbuilder.  Albeit the documentation around the function is misleading.

It looked to be the same case when I looked at the source code for a few other providers as well.
